# Generated by Django 4.2.2 on 2023-06-19 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('protected', 'Protected')], default='public', max_length=10)),
                ('owner', models.IntegerField()),
                ('music', models.FileField(upload_to='musics/')),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicals.music')),
            ],
        ),
    ]
